# Funding
# Add sponsors / donation targets to this file.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# Supported: github, patreon, open_collective, ko_fi, tidelift, community_bridge, liberapay, issuehunt, buy_me_a_coffee, thanks_dev, polar, custom
github: badhope
buy_me_a_coffee: badhope
