// 共享常量与辅助函数
// 从原 index.ts 移动而来，供各 slice 文件引用

import type {
  ThemePreset,
  Category,
  Tag,
} from '../types';

// 默认浅色主题
export const defaultTheme: ThemePreset = {
  id: 'default-light',
  name: 'Light',
  type: 'light',
  colors: {
    primary: '#5B6CFF',
    primaryDark: '#3B4DDB',
    primaryLight: '#8B97FF',
    onPrimary: '#FFFFFF',
    secondary: '#9D7BFF',
    accent: '#FF6B9D',
    background: '#F7F8FC',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    cardElevated: '#FFFFFF',
    text: '#0F172A',
    textSecondary: '#64748B',
    textTertiary: '#94A3B8',
    textDisabled: '#CBD5E1',
    border: '#E2E8F0',
    borderStrong: '#CBD5E1',
    error: '#EF4444',
    warning: '#F59E0B',
    success: '#10B981',
    info: '#0EA5E9',
    divider: '#F1F5F9',
    overlay: 'rgba(15, 23, 42, 0.55)',
    glassBackground: 'rgba(255, 255, 255, 0.85)',
    glassBorder: 'rgba(255, 255, 255, 0.5)',
    shimmer: '#F1F5F9',
    priorities: {
      low: '#10B981',
      medium: '#F59E0B',
      high: '#F97316',
      urgent: '#EF4444',
      critical: '#DC2626',
    },
    status: {
      todo: '#94A3B8',
      'in-progress': '#5B6CFF',
      waiting: '#F59E0B',
      delegated: '#9D7BFF',
      completed: '#10B981',
      cancelled: '#EF4444',
      'on-hold': '#64748B',
    },
    categories: {},
  },
  typography: {
    fontFamily: 'System',
    fontSizeXs: 11,
    fontSizeSm: 13,
    fontSizeBase: 15,
    fontSizeLg: 17,
    fontSizeXl: 20,
    fontSize2xl: 24,
    fontSize3xl: 30,
    fontSize4xl: 36,
    fontWeightLight: 300,
    fontWeightNormal: 400,
    fontWeightMedium: 500,
    fontWeightSemibold: 600,
    fontWeightBold: 700,
    lineHeightTight: 1.2,
    lineHeightNormal: 1.45,
    lineHeightRelaxed: 1.7,
    letterSpacingTight: -0.4,
    letterSpacingNormal: 0,
    letterSpacingWide: 0.4,
  },
  spacing: {
    space1: 4,
    space2: 8,
    space3: 12,
    space4: 16,
    space5: 20,
    space6: 24,
    space7: 28,
    space8: 32,
    space10: 40,
    space12: 48,
    space16: 64,
  },
  borderRadius: {
    none: 0,
    xs: 6,
    sm: 8,
    base: 12,
    md: 14,
    lg: 18,
    xl: 22,
    '2xl': 28,
    full: 9999,
  },
  shadows: {
    none: 'transparent',
    xs: '0 1px 2px 0 rgba(15, 23, 42, 0.04)',
    sm: '0 1px 3px 0 rgba(15, 23, 42, 0.06), 0 1px 2px 0 rgba(15, 23, 42, 0.04)',
    base: '0 2px 4px -1px rgba(15, 23, 42, 0.06), 0 1px 2px 0 rgba(15, 23, 42, 0.04)',
    md: '0 6px 12px -2px rgba(15, 23, 42, 0.08), 0 3px 6px -1px rgba(15, 23, 42, 0.04)',
    lg: '0 12px 20px -4px rgba(15, 23, 42, 0.10), 0 6px 8px -2px rgba(15, 23, 42, 0.05)',
    xl: '0 24px 32px -6px rgba(15, 23, 42, 0.12), 0 12px 12px -4px rgba(15, 23, 42, 0.05)',
    '2xl': '0 32px 48px -8px rgba(15, 23, 42, 0.15), 0 16px 16px -4px rgba(15, 23, 42, 0.05)',
    inner: 'inset 0 2px 4px 0 rgba(15, 23, 42, 0.04)',
    ring: '0 0 0 3px rgba(91, 108, 255, 0.18)',
  },
  isCustom: false,
  isSystem: true,
  createdAt: new Date(),
};

// 默认深色主题
export const darkTheme: ThemePreset = {
  id: 'default-dark',
  name: 'Dark',
  type: 'dark',
  colors: {
    primary: '#8B97FF',
    primaryDark: '#5B6CFF',
    primaryLight: '#A8B1FF',
    onPrimary: '#0F172A',
    secondary: '#B79DFF',
    accent: '#FF8FB3',
    background: '#0B1020',
    surface: '#161B2E',
    card: '#1B2138',
    cardElevated: '#222842',
    text: '#F1F5F9',
    textSecondary: '#94A3B8',
    textTertiary: '#64748B',
    textDisabled: '#475569',
    border: '#2A3050',
    borderStrong: '#3B4366',
    error: '#F87171',
    warning: '#FBBF24',
    success: '#34D399',
    info: '#38BDF8',
    divider: '#1F2540',
    overlay: 'rgba(0, 0, 0, 0.75)',
    glassBackground: 'rgba(22, 27, 46, 0.85)',
    glassBorder: 'rgba(255, 255, 255, 0.08)',
    shimmer: '#1F2540',
    priorities: {
      low: '#34D399',
      medium: '#FBBF24',
      high: '#FB923C',
      urgent: '#F87171',
      critical: '#EF4444',
    },
    status: {
      todo: '#64748B',
      'in-progress': '#8B97FF',
      waiting: '#FBBF24',
      delegated: '#B79DFF',
      completed: '#34D399',
      cancelled: '#F87171',
      'on-hold': '#475569',
    },
    categories: {},
  },
  typography: {
    fontFamily: 'System',
    fontSizeXs: 11,
    fontSizeSm: 13,
    fontSizeBase: 15,
    fontSizeLg: 17,
    fontSizeXl: 20,
    fontSize2xl: 24,
    fontSize3xl: 30,
    fontSize4xl: 36,
    fontWeightLight: 300,
    fontWeightNormal: 400,
    fontWeightMedium: 500,
    fontWeightSemibold: 600,
    fontWeightBold: 700,
    lineHeightTight: 1.2,
    lineHeightNormal: 1.45,
    lineHeightRelaxed: 1.7,
    letterSpacingTight: -0.4,
    letterSpacingNormal: 0,
    letterSpacingWide: 0.4,
  },
  spacing: {
    space1: 4,
    space2: 8,
    space3: 12,
    space4: 16,
    space5: 20,
    space6: 24,
    space7: 28,
    space8: 32,
    space10: 40,
    space12: 48,
    space16: 64,
  },
  borderRadius: {
    none: 0,
    xs: 6,
    sm: 8,
    base: 12,
    md: 14,
    lg: 18,
    xl: 22,
    '2xl': 28,
    full: 9999,
  },
  shadows: {
    none: 'transparent',
    xs: '0 1px 2px 0 rgba(0, 0, 0, 0.20)',
    sm: '0 1px 3px 0 rgba(0, 0, 0, 0.30), 0 1px 2px 0 rgba(0, 0, 0, 0.20)',
    base: '0 2px 4px -1px rgba(0, 0, 0, 0.30), 0 1px 2px 0 rgba(0, 0, 0, 0.20)',
    md: '0 6px 12px -2px rgba(0, 0, 0, 0.35), 0 3px 6px -1px rgba(0, 0, 0, 0.20)',
    lg: '0 12px 20px -4px rgba(0, 0, 0, 0.40), 0 6px 8px -2px rgba(0, 0, 0, 0.25)',
    xl: '0 24px 32px -6px rgba(0, 0, 0, 0.45), 0 12px 12px -4px rgba(0, 0, 0, 0.25)',
    '2xl': '0 32px 48px -8px rgba(0, 0, 0, 0.50), 0 16px 16px -4px rgba(0, 0, 0, 0.25)',
    inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.20)',
    ring: '0 0 0 3px rgba(139, 151, 255, 0.25)',
  },
  isCustom: false,
  isSystem: true,
  createdAt: new Date(),
};

// 初始分类数据
export const initialCategories: Category[] = [
  {
    id: 'cat-1',
    name: '工作',
    description: '工作相关任务',
    color: '#3B82F6',
    icon: 'briefcase',
    parentCategoryId: null,
    childCategoryIds: [],
    isSystem: true,
    isArchived: false,
    taskCount: 0,
    order: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    projectId: null,
  },
  {
    id: 'cat-2',
    name: '个人',
    description: '个人生活任务',
    color: '#10B981',
    icon: 'user',
    parentCategoryId: null,
    childCategoryIds: [],
    isSystem: true,
    isArchived: false,
    taskCount: 0,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    projectId: null,
  },
  {
    id: 'cat-3',
    name: '学习',
    description: '学习和教育任务',
    color: '#F59E0B',
    icon: 'book',
    parentCategoryId: null,
    childCategoryIds: [],
    isSystem: true,
    isArchived: false,
    taskCount: 0,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
    projectId: null,
  },
  {
    id: 'cat-4',
    name: '健康',
    description: '健康和运动',
    color: '#EF4444',
    icon: 'heart',
    parentCategoryId: null,
    childCategoryIds: [],
    isSystem: true,
    isArchived: false,
    taskCount: 0,
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
    projectId: null,
  },
  {
    id: 'cat-5',
    name: '购物',
    description: '购物和杂项',
    color: '#8B5CF6',
    icon: 'shopping-cart',
    parentCategoryId: null,
    childCategoryIds: [],
    isSystem: true,
    isArchived: false,
    taskCount: 0,
    order: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
    projectId: null,
  },
];

// 初始标签数据
export const initialTags: Tag[] = [
  { id: 'tag-1', name: '紧急', color: '#EF4444', icon: 'alert-circle', isSystem: true, usageCount: 0, createdAt: new Date(), updatedAt: new Date(), createdBy: null },
  { id: 'tag-2', name: '重要', color: '#F59E0B', icon: 'star', isSystem: true, usageCount: 0, createdAt: new Date(), updatedAt: new Date(), createdBy: null },
  { id: 'tag-3', name: '待定', color: '#6B7280', icon: 'clock', isSystem: true, usageCount: 0, createdAt: new Date(), updatedAt: new Date(), createdBy: null },
  { id: 'tag-4', name: '灵感', color: '#8B5CF6', icon: 'lightbulb', isSystem: true, usageCount: 0, createdAt: new Date(), updatedAt: new Date(), createdBy: null },
];

// 存储键常量
export const STORAGE_KEYS = {
  USER: 'taskflow_user',
  TASKS: 'taskflow_tasks',
  VAULT: 'taskflow_vault',
  PROJECTS: 'taskflow_projects',
  CATEGORIES: 'taskflow_categories',
  TAGS: 'taskflow_tags',
  VIEWS: 'taskflow_views',
  CALENDARS: 'taskflow_calendars',
  EVENTS: 'taskflow_events',
  REMINDERS: 'taskflow_reminders',
  GOALS: 'taskflow_goals',
  HABITS: 'taskflow_habits',
  NOTES: 'taskflow_notes',
  THEME: 'taskflow_theme',
  SYNC_CONFIG: 'taskflow_sync_config',
  LAST_SYNC: 'taskflow_last_sync',
  AUTOMATION: 'taskflow_automation',
  TEMPLATES: 'taskflow_templates',
  TEAMS: 'taskflow_teams',
  SESSIONS: 'taskflow_sessions',
  USER_PREFERENCES: 'taskflow_user_preferences',
  SIDEBAR_OPEN: 'taskflow_sidebar_open',
  SEARCH_HISTORY: 'taskflow_search_history',
};

// 生成唯一 ID：优先 crypto.randomUUID()，降级到时间戳+随机串
export const generateId = (): string =>
  typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function'
    ? crypto.randomUUID()
    : `${Date.now()}-${Math.random().toString(36).slice(2, 11)}`;

// 深拷贝辅助函数
export const deepClone = <T>(obj: T): T => {
  if (typeof structuredClone === 'function') {
    return structuredClone(obj);
  }
  return JSON.parse(JSON.stringify(obj));
};
